<<<<<<< HEAD
# Generated by Django 3.1.6 on 2021-02-17 11:42
=======
# Generated by Django 3.1.6 on 2021-02-14 19:21
>>>>>>> 71b93ec3817ca29eb7f4c9007e65ab0a22ddc553

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('active', models.BooleanField(default=True)),
=======
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(unique=True)),
                ('last_name', models.TextField()),
                ('email', models.TextField()),
                ('mobile', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
>>>>>>> 71b93ec3817ca29eb7f4c9007e65ab0a22ddc553
            ],
        ),
    ]
