# Generated by Django 3.1.6 on 2021-02-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('api_key', models.CharField(blank=True, max_length=201, null=True)),
                ('recipients', models.TextField(blank=True, max_length=1000, null=True)),
                ('message', models.TextField(blank=True, max_length=200, null=True)),
                ('sender_id', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
