# Generated by Django 3.1.6 on 2021-02-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter1app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_user',
            name='phone_number',
            field=models.CharField(default=None, max_length=13, unique=True),
        ),
    ]
