# Generated by Django 3.1.6 on 2021-02-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter1app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=8, unique=True)),
                ('phone_number', models.CharField(default=None, max_length=8, unique=True)),
                ('email', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('profile_pic', models.ImageField(blank='true', upload_to='new_post/')),
                ('bio', models.TextField()),
            ],
        ),
    ]
