# Generated by Django 3.1.6 on 2021-02-17 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter1app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='count',
            old_name='name',
            new_name='username',
        ),
    ]
