# Generated by Django 3.1.6 on 2021-02-16 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter1app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='cname',
            new_name='name',
        ),
    ]
