# Generated by Django 3.1.6 on 2021-02-16 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter1app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talking',
            old_name='recepients',
            new_name='recipients',
        ),
    ]
