# Generated by Django 3.1.6 on 2021-02-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter1app', '0002_add_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_user',
            name='phone_number',
            field=models.CharField(default=None, max_length=10, unique=True),
        ),
    ]
