# Generated by Django 3.1.6 on 2021-02-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter1app', '0002_auto_20210224_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='talking',
            name='topup_amount',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='talking',
            name='message',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='talking',
            name='recipients',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
