# Generated by Django 3.1.6 on 2021-02-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter1app', '0002_auto_20210216_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='contact',
        ),
        migrations.AddField(
            model_name='group',
            name='contact',
            field=models.ManyToManyField(to='counter1app.Contact'),
        ),
    ]
