# Generated by Django 3.1.6 on 2021-02-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter1app', '0003_auto_20210225_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_user',
            name='username',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
