# Generated by Django 3.1.6 on 2021-02-17 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter1app', '0003_auto_20210217_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='contact',
        ),
        migrations.AddField(
            model_name='group',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='counter1app.contact'),
        ),
    ]
