# Generated by Django 3.1.6 on 2021-02-23 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter1app', '0005_auto_20210219_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='counter1app.profile'),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
