# Generated by Django 3.1.6 on 2021-02-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter1app', '0006_auto_20210223_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='contact',
        ),
        migrations.AddField(
            model_name='group',
            name='contact',
            field=models.ManyToManyField(to='counter1app.Profile'),
        ),
    ]
